### PR TITLE
Firing CDI events on BeforeCommit, AfterCommit and AfterRollback.

### PR DESCRIPTION
**Pull request by rafaelGuerreiro**
I also added one more test case, improved the setUp() on the tests and tested if the events were fired only when needed.

### CODE REVIEW

**Comment by Turini** [comment]
Sounds nice to me, could you just add some docs about that on README?

**Comment by rafaelGuerreiro** [comment]
Sure!!

**Comment by csokol** [comment]
I havent seen the code yet but it seems to be a great idea! I dont know why
but this reminds me the beforeredirectlistener from the core. I think we
should fire an event and deprecate the listener, what do you think?

Em 10:06 ter, 24/02/2015, Rodrigo Turini <notifications
<notifications@github.com>@ <notifications@github.com>github.com
<notifications@github.com>> escreveu:

**Comment by rafaelGuerreiro** [comment]
@Turini, I've added the docs. Could you please validate it?

**Comment by lucascs** [comment]
seems :ok_hand:  to me =)

**Comment by Turini** [comment]
thanks @rafaelGuerreiro, it looks great!

**Comment by Turini** [comment]
> I havent seen the code yet but it seems to be a great idea! I dont know 
why but this reminds me the beforeredirectlistener from the core. I think 
we should fire an event and deprecate the listener, what do you think?

@csokol, which listener are you talking about?

**Comment by csokol** [comment]
Sorry, I was on mobile. The right name is RedirectListener:
https://github.com/caelum/vraptor4/blob/master/vraptor-core/src/main/java/br/com/caelum/vraptor/http/VRaptorResponse.java#L52

I think we could deprecate that listener and that method to add the
listener and create a new event to fire before redirect.

**Comment by Turini** [comment]
hum, now I see your point @csokol. 
I've just opened an issue https://github.com/caelum/vraptor4/issues/950 to track this

**Comment by garcia-jj** [comment]
@Turini can you release a new version for this plugin? Can help users with this feature.

**Comment by Turini** [comment]
Sure! I'll do it asap

**Comment by Turini** [comment]
I've just released vs 4.0.4:
https://github.com/caelum/vraptor-jpa/releases/tag/vraptor-jpa-4.0.4
it'l be available on maven's repo in a few hours. thks

**Pull request merged**
